### ISSUE TITLE
tiup: deployment of tiproxy might be incomplete

### ISSUE THREAD

**Issue by dveeden** [pingcap/docs#20084]
## Error Report

1. What is the URL/path of the document related to this issue?

https://docs.pingcap.com/tidb/stable/tiproxy-overview#deploy-tiproxy

2. How would you like to improve it?

It looks like something like this is missing:
```
tiproxy_servers:
  - host: 192.168.122.196
```

Maybe besides "Configure the TiProxy instances." there should also be a "Define TiProxy instances"?

See also: https://docs.pingcap.com/tidb/stable/tiup-cluster-topology-reference#tiproxy_servers

cc @djshow832 @qiancai

**Comment by dveeden** [comment]
Related issue:

https://docs.pingcap.com/tidb/stable/tiup-cluster-topology-reference#tiproxy_servers says there is a `data_dir` under `tiproxy_servers`.

But https://github.com/pingcap/tiup/blob/8e15a038a9fcd7c4562fc9839263609fb9eafe37/pkg/cluster/spec/tiproxy.go#L73-L84 doesn't show this.

When deploying it leads to this:
```
$ tiup cluster check tidb-dba scale-out-tiproxy.yaml --cluster
Checking updates for component cluster...
Error: Failed to parse topology file scale-out-tiproxy.yaml (topology.parse_failed)
  caused by: yaml: unmarshal errors:
  line 5: field data_dir not found in type spec.TiProxySpec

Please check the syntax of your topology file scale-out-tiproxy.yaml and try again.
```

```yaml
tiproxy_servers:
  - host: 10.0.0.1
    deploy_dir: "/tiproxy-deploy"
    data_dir: "/tiproxy-data"
    port: 3306
    status_port: 3080
    config:
      log.level: warn
      log.format: json
```
