### ISSUE TITLE
deploy-tiflash docs in tidb-in-kubernetes don't discuss nodeSelector/tolerations

### ISSUE THREAD

**Issue by kolbe** [pingcap/docs#5069]
## Change Request

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

https://docs.pingcap.com/tidb-in-kubernetes/stable/deploy-tiflash gives this suggestion for the section to add to the TidbCluster resource to add TiFlash to the cluster:

```
spec:
  tiflash:
    baseImage: pingcap/tiflash
    maxFailoverCount: 3
    replicas: 1
    storageClaims:
    - resources:
        requests:
          storage: 100Gi
      storageClassName: local-storage
```

If I've followed the steps at https://docs.pingcap.com/tidb-in-kubernetes/stable/deploy-on-aws-eks, or even just done the logical copy/paste/transform in my tidb-cluster.yaml file, I'll end up with a situation where tidb-operator is trying to schedule tiflash pods to nodes that are not configured to tolerate them.

2. Describe your suggestion or addition.

I suppose https://docs.pingcap.com/tidb-in-kubernetes/stable/deploy-tiflash needs to somehow accommodate deployments that have various permutations of node selectors and tolerations.

This is probably a problem well beyond this specific page.

I don't have any good suggestion for how to keep the documentation clear while also accounting for all these different possibilities 🙁 

3. Provide some reference materials (documents, websites, etc) if you could.
